[package]
name = "p256"
description = "NIST P-256 (secp256r1) elliptic curve"
version = "0.3.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p256"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "prime256v1", "secp256r1"]

[dependencies]
ecdsa = { version = "= 0.7.0-pre", optional = true, default-features = false }
elliptic-curve = { version = "= 0.5.0-pre", default-features = false,  features = ["weierstrass"] }
sha2 = { version = "0.9", optional = true }
zeroize = { version = "1",  optional = true, default-features = false }

[dev-dependencies]
ecdsa = { version = "= 0.7.0-pre", default-features = false, features = ["dev", "hazmat"] }
hex = "0.4" # TODO: switch to hex-literal
hex-literal = "0.2"
proptest = "0.10"

[features]
default = ["arithmetic", "std"]
arithmetic = []
rand = ["elliptic-curve/rand_core"]
sha256 = ["ecdsa/digest", "ecdsa/hazmat", "sha2"]
test-vectors = []
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
